# Generated by Django 4.2.8 on 2024-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThietLapMucHocPhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heDaoTao", models.CharField(max_length=100)),
                ("namHoc", models.CharField(max_length=100)),
                ("tenNganh", models.CharField(max_length=100)),
                ("khoa", models.CharField(max_length=100)),
                ("lop", models.CharField(max_length=100)),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
                ("isNganhHai", models.BooleanField(blank=True)),
                ("isHocLai", models.BooleanField(blank=True)),
                ("isMienGiam", models.BooleanField(blank=True)),
                ("hocKy", models.BooleanField(blank=True)),
                ("tinhChat", models.CharField(max_length=100)),
                ("heSo", models.IntegerField(blank=True)),
                ("soTien", models.BigIntegerField(blank=True)),
            ],
        ),
    ]
