# Generated by Django 4.2.8 on 2024-01-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ThietLapMucHocPhi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thietlapmuchocphi",
            name="isChatLuongCao",
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thietlapmuchocphi",
            name="isMonGDTC",
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
