# Generated by Django 4.2.8 on 2024-02-19 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DanhMucThuChi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenKhoan", models.CharField(max_length=100)),
                ("isKhoanThu", models.BooleanField(blank=True)),
                ("isKhoanChi", models.BooleanField(blank=True)),
                ("isKhoanThuNhapHoc", models.BooleanField(blank=True)),
                ("isHocPhi", models.BooleanField(blank=True)),
                ("isThuTrucTuyen", models.BooleanField(blank=True)),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HeDaoTao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenHeDaoTao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Khoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenKhoa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="KhoaHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namKhoaHoc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Lop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lop", models.CharField(max_length=100)),
                (
                    "heDaoTao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.hedaotao"
                    ),
                ),
                (
                    "khoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.khoa"
                    ),
                ),
                (
                    "khoaHoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.khoahoc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NamHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namHoc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ThietLapMucHocPhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heDaoTao", models.CharField(max_length=100)),
                ("namHoc", models.CharField(max_length=100)),
                ("tenNganh", models.CharField(max_length=100)),
                ("khoa", models.CharField(max_length=100)),
                ("lop", models.CharField(max_length=100)),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
                ("isNganhHai", models.BooleanField(blank=True)),
                ("isHocLai", models.BooleanField(blank=True)),
                ("isMonGDTC", models.BooleanField(blank=True)),
                ("isChatLuongCao", models.BooleanField(blank=True)),
                ("isMienGiam", models.BooleanField(blank=True)),
                ("hocKy", models.BooleanField(blank=True)),
                ("tinhChat", models.CharField(max_length=100)),
                ("heSo", models.IntegerField(blank=True)),
                ("soTien", models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SinhVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maSV", models.CharField(max_length=10)),
                ("hoTen", models.CharField(max_length=100)),
                ("ngaySinh", models.DateField(blank=True, null=True)),
                ("queQuan", models.CharField(max_length=100)),
                ("trangThai", models.BooleanField(blank=True)),
                (
                    "lop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.lop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NganhDaoTao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenNganhDaoTao", models.CharField(max_length=100)),
                (
                    "heDaoTao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.hedaotao"
                    ),
                ),
                (
                    "khoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.khoa"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lop",
            name="nganhDaoTao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.nganhdaotao"
            ),
        ),
        migrations.CreateModel(
            name="KhoanThuNhapHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dotNhapHoc", models.IntegerField()),
                ("soTien", models.BigIntegerField()),
                (
                    "khoaHoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.khoahoc"
                    ),
                ),
                (
                    "khoanThu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.danhmucthuchi",
                    ),
                ),
                (
                    "nganhDaoTao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.nganhdaotao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KhoanThuHocPhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hanNop", models.DateField(blank=True, null=True)),
                ("noiDungThu", models.CharField(blank=True, max_length=100, null=True)),
                ("ghiChu", models.CharField(blank=True, max_length=100, null=True)),
                ("maSoThue", models.CharField(max_length=10)),
                ("soTienMienGiam", models.BigIntegerField()),
                ("soTien", models.BigIntegerField()),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
                ("trangThai", models.BooleanField(blank=True)),
                (
                    "mucHocPhi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.thietlapmuchocphi",
                    ),
                ),
                (
                    "sinhVien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sinhvien"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeHoachThu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dotThu", models.IntegerField()),
                ("trangThai", models.BooleanField(blank=True, null=True)),
                ("soTien", models.BigIntegerField()),
                ("ngayBatDau", models.DateField(blank=True, null=True)),
                ("ngayKetThuc", models.DateField(blank=True, null=True)),
                ("noiDung", models.TextField()),
                (
                    "khoaHoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.khoahoc"
                    ),
                ),
                (
                    "khoanThu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.danhmucthuchi",
                    ),
                ),
                (
                    "nganhDaoTao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.nganhdaotao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTraHocPhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soPhieu", models.CharField(blank=True, max_length=100, null=True)),
                ("noiDungChi", models.CharField(blank=True, max_length=100, null=True)),
                ("ghiChu", models.CharField(blank=True, max_length=100, null=True)),
                ("soTienDaNop", models.BigIntegerField()),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "khoanThuHocPhi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.khoanthuhocphi",
                    ),
                ),
                (
                    "sinhVien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sinhvien"
                    ),
                ),
            ],
        ),
    ]
