# Generated by Django 4.2.8 on 2024-02-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitrahocphi",
            name="trangThai",
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
