# Generated by Django 4.2.8 on 2024-02-19 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_chitrahocphi_trangthai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chitrahocphi",
            name="trangThai",
        ),
    ]
