# Generated by Django 4.2.8 on 2024-01-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ThongTin", "0001_initial"),
        ("KhoanThuHocPhi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiTraHocPhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soPhieu", models.CharField(blank=True, max_length=100, null=True)),
                ("noiDungChi", models.CharField(blank=True, max_length=100, null=True)),
                ("ghiChu", models.CharField(blank=True, max_length=100, null=True)),
                ("soTienDaNop", models.BigIntegerField()),
                ("trangThai", models.BooleanField(blank=True, null=True)),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "khoanThuHocPhi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="KhoanThuHocPhi.khoanthuhocphi",
                    ),
                ),
                (
                    "sinhVien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SinhVien.sinhvien",
                    ),
                ),
            ],
        ),
    ]
