# Generated by Django 4.2.8 on 2024-01-30 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ChiTraHocPhi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chitrahocphi",
            name="trangThai",
        ),
    ]
