# Generated by Django 4.2.8 on 2024-01-25 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ThongTin", "0001_initial"),
        ("ThietLapMucHocPhi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KhoanThuHocPhi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hanNop", models.DateField(blank=True, null=True)),
                ("noiDungThu", models.CharField(blank=True, max_length=100, null=True)),
                ("ghiChu", models.CharField(blank=True, max_length=100, null=True)),
                ("maSoThue", models.CharField(max_length=10)),
                ("soTienMienGiam", models.BigIntegerField()),
                ("soTien", models.BigIntegerField()),
                ("trangThai", models.BooleanField(blank=True, null=True)),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "mucHocPhi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ThietLapMucHocPhi.thietlapmuchocphi",
                    ),
                ),
                (
                    "sinhVien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SinhVien.sinhvien",
                    ),
                ),
            ],
        ),
    ]
