# Generated by Django 4.2.8 on 2024-01-30 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("KhoanThuHocPhi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="khoanthuhocphi",
            name="trangThai",
        ),
    ]
