# Generated by Django 4.2.8 on 2024-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DanhMucThuChi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenKhoan", models.CharField(max_length=100)),
                ("isKhoanThu", models.BooleanField(blank=True)),
                ("isKhoanChi", models.BooleanField(blank=True)),
                ("isKhoanThuNhapHoc", models.BooleanField(blank=True)),
                ("isHocPhi", models.BooleanField(blank=True)),
                ("isThuTrucTuyen", models.BooleanField(blank=True)),
                ("ngayThem", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
